### ISSUE TITLE
km occur error in my pipeline

### ISSUE THREAD

**Issue by Zhengfy1022** [iric-soft/km#24]
**Describe the bug**
I ran km with output of jellyfish which command is :
jellyfish count -m 31 -o ${OUTPUTS}/${SAMPLE}/${SAMPLE}_countTable31.jf -s 100M -t $3 -C -L 2 r1.fq r2.fq
km find_mutation ALL_targets/focal_deletions/ ${OUTPUTS}/${SAMPLE}/${SAMPLE}_countTable31.jf
It always occur the same error when I input different target base

**To Reproduce**
1. What is your target sequence ?

Filename: IKZF1_exon3_exon8.fa
>chr7:50367318-50367353 IKZF1_exon3
GAGGACAGCAAAGCTCCAAGAGTGACAGAGTCGTGG
>chr7:50467616-50467650 IKZF1_exon8
GGGACAAGGGCCTGTCCGACACGCCCTACGACAGC

Filename: IKZF1_exon1_exon8.fa
>hg19_dna range=chr7:50344487-50344519 IKZF1_exon1_5UTR
TCTTGGCCCCAAAGCGCGACGCACAAATCCACG
>hg19_dna range=chr7:50467616-50467648 IKZF1_exon8
GGACAAGGGCCTGTCCGACACGCCCTACGACA

Filename: IKZF1_exon1_exon4.fa
>hg19_dna range=chr7:50344488-50344518 5'pad=30 3'pad=0 strand=+ repeatMasking=none
CTTGGCCCCAAAGCGCGACGCACAAATCCAC
>hg19_dna range=chr7:50444231-50444261 5'pad=0 3'pad=30 strand=+ repeatMasking=none
CCAGTAATGTTAAAGTAGAGACTCAGAGTGA

2. What type of mutation do you expect ?
exon deletion
3. See error
Traceback (most recent call last):
  File "/path/to/software/RaScALL/.virtualenvs/km/bin/km", line 33, in <module>
    sys.exit(load_entry_point('km-walk==2.2.0', 'console_scripts', 'km')())
  File "/path/to/software/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/km.py", line 67, in main
    args.func(args, parser)
  File "/path/to/software/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/tools/find_mutation.py", line 41, in main_find_mut
    ref_seqs, ref_attr = uc.file_2_seq(seq_f)
  File "/path/to/software/RaScALL/.virtualenvs/km/lib/python3.7/site-packages/km/utils/common.py", line 41, in file_2_seq
    k, v = x.split("=")
ValueError: too many values to unpack (expected 2)

**Expected behavior**
Use the software to detect alternative splices or exon(s) deletion in my sample data.

**Desktop (please complete the following information):**
 - OS
 CentOS
 - python version
 3.7 
 - lib version
 hg19

**Comment by Zhengfy1022** [comment]
Oh I see. The problem lies in my sequence name which contains too many equal signs. After I changed the sequence name, the program ran normally
