### ISSUE TITLE
difficulty installing with easy_install.sh

### ISSUE THREAD

**Issue by bibbers93** [iric-soft/km#8]
**Describe the bug**
I have downloaded the easy_install.sh script and made it executable on my linux system.
Python 2.7.6 is loaded and I am using gcc v4.9.1 

I have ran this easy_install.sh script ```./easy_install.sh``` and receive a number of errors to screen. 

Notably, it appears that jellyfish 2.2.6 has downloaded fine and in the final part of the script titled "download and install km" I get a number of errors which I cannot resolve. 

```
 make[2]: Leaving directory `/disk/home/s1667153/software/jellyfish-2.2.6'                                                                                                                [42/1892]
make[1]: Leaving directory `/disk/home/s1667153/software/jellyfish-2.2.6'
Initialized empty Git repository in /disk/home/s1667153/software/km/.git/
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1282 (delta 2), reused 1 (delta 1), pack-reused 1277
Receiving objects: 100% (1282/1282), 1.74 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (818/818), done.
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    'km=km.km:main',
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/dist.py", line 720, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/s1667153/.virtualenvs/km/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5Jiyir/numpy-1.17.3/setup.py", line 31, in <module>
    author='Eric Audemard, Patrick Gendron, Sebastien Lemieux',
RuntimeError: Python version >= 3.5 required.
```
Note, it says runtime error python v3.5 required, when this is re-ran with python 3.5.6 jelly fish downloads fine but the same message about python versions is sent to screen and there are a series of ```SYNTAX``` errors also

e.g. 
```
SyntaxError: invalid syntax
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/disk/install/modules/apps/gcc/python/3.6.5/lib/python3.6/site-packages/km-0.1.0-py3.6.egg/km/tools/find_mutation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/disk/install/modules/apps/gcc/python/3.6.5/lib/python3.6/site-packages/km-0.1.0-py3.6.egg/km/utils/MutationFinder.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/disk/install/modules/apps/gcc/python/3.6.5/lib/python3.6/site-packages/km-0.1.0-py3.6.egg/km/utils/Graph.py", line 24
    def __getitem__(self, (i, j)):
```

Would you be able to advise?

**Comment by ericloud** [comment]
Firstly, km doesn't work on python3, we use some python2 syntaxe which doesn't work in python3.

Next, it seems that you have some difficulty with numpy.
In your error message we can see that you use "numpy1.17.3": 
 - File "/tmp/easy_install-5Jiyir/numpy-1.17.3/setup.py", line 31, in <module>
and since  [numpy 1.17.2](https://github.com/numpy/numpy/releases/tag/v1.17.2): "The Python versions supported in this release are 3.5-3.7, Python 2.7 has been dropped."
Which explain why the error message ask you to switch on python3 : "I suppose that numpy 1.17.3 is python3 specific"

I don't know why numpy 1.17.3 is use, as km setup.py ask for 1.13.3:
 - https://github.com/iric-soft/km/blob/3700eb87a53fe3b4d0cdf2b23240b9c002b90c6a/setup.py#L79

A way to fixe it, is to force the installation numpy 1.13.3, adding `pip install numpy==1.13.3`
just after: https://github.com/iric-soft/km/blob/3700eb87a53fe3b4d0cdf2b23240b9c002b90c6a/easy_install.sh#L14

**Comment by ericloud** [comment]
We found the issue and it's fixed. 
Could you download the new version and tell me if the fix works on your side ?

**Comment by bibbers93** [comment]
Hi Eric, 

We have tried this again this morning using Python v2.7.6 and gcc v4.9.1, and then again with gcc v5.5.0 but we continue to get errors. 

There are a number of __configtest.c warnings re: "conflicting types for built-in functions" and a series of unused numpy variables that are reported to screen. 

The final line output however states the set up script exited with error. Would you be able to comment? Please see the attached file. 

Thanks

[easy_install_errors.txt](https://github.com/iric-soft/km/files/3808421/easy_install_errors.txt)

**Comment by ericloud** [comment]
Hi, 

Sorry for the late answer, I was in vacation yesterday.
I have the same type of warning when previously compiled library are used (in `$INSTALL_DIR/software/km` and `$INSTALL_DIR/software/jellyfish-2.2.6`). 

I have updated easy_install.sh to avoid it.
https://github.com/iric-soft/km/blob/aa3c8f7ec17d54e862aaa6ce9d8259e361dcbe3c/easy_install.sh#L10

Could you remove these folders (or download the new version), and try again ? 
I'm not sure that fix everything, but the error will be easiest to understand after this cleaning. 

Sorry for giving you so much trouble,
Eric.

**Comment by bibbers93** [comment]
Hi Eric, sorry for the delay in responding i have been at a conference this past week. 

I believe we have managed to get it working on our system based on the version you posted last. 

Our server manager has told me that we have to use 

```. /disk/install/modules/apps/gcc/km/1.0/.virtualenvs/km/bin/activate```

 to set it up and in doing so I can now access the km help manual ($km -h). I'll start using it on my samples and let you know if any other issues arise! 

Thanks for your help :)

**Comment by ericloud** [comment]
Welcome, 

It's nice to read.

If I understand correctly your last message, to install km on your system you need to edit [easy_install.sh](https://github.com/iric-soft/km/blob/master/easy_install.sh) to replace https://github.com/iric-soft/km/blob/aa3c8f7ec17d54e862aaa6ce9d8259e361dcbe3c/easy_install.sh#L6
by `INSTALL_DIR="/disk/install/modules/apps/gcc/km/1.0/"`

Thanks for you feedback. If you see a way to improve the documentation on this point, I invite you (or you server manager) to propose a pull request.

I will close this issue. Fill free to open other issues if you have any other questions.

Eric.
